@baseUrl = http://localhost:5000


### Create learning goal
POST {{baseUrl}}/api/learning-goals
Content-Type: application/json

{
    "title": "Learn Something2",
    "description": "Test2",
    "targetDate": "2026-12-30"
}

### Get all learning goals
GET {{baseUrl}}/api/learning-goals

### Get learning goal
GET {{baseUrl}}/api/learning-goals/d31a7b9b-c67a-41ec-8a33-a1ec46432032

### Update learning goal
PUT {{baseUrl}}/api/learning-goals/d31a7b9b-c67a-41ec-8a33-a1ec46432032
Content-Type: application/json

{
    "title": "Learn Something3",
    "description": "Test2",
    "targetDate": "2026-12-30"
}