@baseUrl = http://localhost:5000


### Create learning goal
# @name createLearningGoal
POST {{baseUrl}}/api/learning-goals
Content-Type: application/json

{
    "title": "Learn Something",
    "description": "Test",
    "targetDate": "2026-12-31"
}

### Get created learning goal
GET {{baseUrl}}/api/learning-goals/{{createLearningGoal.response.body.$.id}}
